# Generated by Django 6.0 on 2026-02-06 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('delivered_to', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
                ('forwarded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.REALTIME_CHAT_MESSAGING_MESSAGE_MODEL)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_replies', to=settings.REALTIME_CHAT_MESSAGING_MESSAGE_MODEL)),
            ],
            options={
                'abstract': False,
                'swappable': 'REALTIME_CHAT_MESSAGING_MESSAGE_MODEL',
            },
        ),
        migrations.CreateModel(
            name='RoomProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict)),
            ],
            options={
                'swappable': 'REALTIME_CHAT_MESSAGING_ROOMPROPERTY_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('last_message', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.REALTIME_CHAT_MESSAGING_MESSAGE_MODEL)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.REALTIME_CHAT_MESSAGING_ROOMPROPERTY_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='realtime_chat_messaging.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('REACTION', 'Reaction'), ('NEW_MESSAGE', 'New Message'), ('REPLY', 'Reply')], default='NEW_MESSAGE', max_length=64)),
                ('recipients', models.ManyToManyField(related_name='%(app_label)s_%(class)s_unread_messages', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_notifications', to=settings.REALTIME_CHAT_MESSAGING_MESSAGE_MODEL)),
            ],
            options={
                'swappable': 'REALTIME_CHAT_MESSAGING_CHATNOTIFICATION_MODEL',
            },
        ),
        migrations.CreateModel(
            name='MessageMediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('media_url', models.CharField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(default='image/jpeg')),
                ('caption', models.CharField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_attachments', to=settings.REALTIME_CHAT_MESSAGING_MESSAGE_MODEL)),
            ],
            options={
                'swappable': 'REALTIME_CHAT_MESSAGING_MESSAGEMEDIAASSET_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reaction_content', models.TextField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_reactions', to=settings.REALTIME_CHAT_MESSAGING_MESSAGE_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'swappable': 'REALTIME_CHAT_MESSAGING_REACTION_MODEL',
            },
        ),
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_read_receipts', to=settings.REALTIME_CHAT_MESSAGING_MESSAGE_MODEL)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'swappable': 'REALTIME_CHAT_MESSAGING_READRECEIPT_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField()),
                ('last_seen', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'swappable': 'REALTIME_CHAT_MESSAGING_SESSION_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realtime_chat_messaging.room')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('max_subscribers', models.PositiveBigIntegerField(default=300)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_new_subscribers', 'Can add new subscribers'), ('can_remove_subscribers', 'Can remove subscribers'), ('can_send_messages', 'Can send messages')],
                'abstract': False,
                'swappable': 'REALTIME_CHAT_MESSAGING_CHANNEL_MODEL',
            },
            bases=('realtime_chat_messaging.room', models.Model),
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realtime_chat_messaging.room')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_participants', models.PositiveBigIntegerField(default=100)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('join_approval_required', models.BooleanField(default=False)),
                ('group_locked', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_new_participants', 'Can add new participants'), ('can_remove_participants', 'Can remove participants')],
                'abstract': False,
                'swappable': 'REALTIME_CHAT_MESSAGING_GROUPCHAT_MODEL',
            },
            bases=('realtime_chat_messaging.room', models.Model),
        ),
        migrations.CreateModel(
            name='OneToOneChat',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realtime_chat_messaging.room')),
                ('participants', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'swappable': 'REALTIME_CHAT_MESSAGING_ONETOONECHAT_MODEL',
            },
            bases=('realtime_chat_messaging.room', models.Model),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['content'], name='realtime_ch_content_e6aad5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['content', 'sender'], name='realtime_ch_content_33f3e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('is_forwarded', True), ('parent_message__isnull', False), _negated=True), name='forwarded_messages_cant_be_replies'),
        ),
        migrations.AddConstraint(
            model_name='messagemediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('mime_type__in', ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/heic', 'audio/mpeg', 'audio/mp4', 'audio/aac', 'audio/ogg', 'audio/wav', 'audio/opus', 'video/mp4', 'video/quicktime', 'video/webm', 'video/ogg', 'video/x-msvideo', 'video/x-matroska', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'text/plain', 'text/csv'])), name='valid_mime_type'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_reaction'),
        ),
        migrations.AddConstraint(
            model_name='readreceipt',
            constraint=models.UniqueConstraint(fields=('message', 'reader'), name='unique_read_receipts'),
        ),
    ]
