# Generated by Django 6.0 on 2026-02-06 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtime_chat_messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRoomProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomChannel',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realtime_chat_messaging.room')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('max_subscribers', models.PositiveBigIntegerField(default=300)),
                ('preferences', models.JSONField(default=dict)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_new_subscribers', 'Can add new subscribers'), ('can_remove_subscribers', 'Can remove subscribers'), ('can_send_messages', 'Can send messages'), ('can_manage_preferences', 'Can manage channel preferences')],
                'abstract': False,
            },
            bases=('realtime_chat_messaging.room', models.Model),
        ),
        migrations.CreateModel(
            name='CustomGroupChat',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realtime_chat_messaging.room')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_participants', models.PositiveBigIntegerField(default=100)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('join_approval_required', models.BooleanField(default=False)),
                ('group_locked', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('admins', models.ManyToManyField(related_name='custom_groups_moderated', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_new_participants', 'Can add new participants'), ('can_remove_participants', 'Can remove participants')],
                'abstract': False,
            },
            bases=('realtime_chat_messaging.room', models.Model),
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField()),
                ('last_seen', models.DateTimeField()),
                ('device_type', models.CharField(default='unknown', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='realtime_chat_messaging.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['content'], name='custom_impl_content_9a4afa_idx'), models.Index(fields=['content', 'sender'], name='custom_impl_content_7286c2_idx')],
            },
        ),
    ]
