# Generated by Django 6.0 on 2026-02-13 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtime_chat_messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], db_index=True, default='normal', help_text='Message priority level', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Custom metadata for the message')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Whether this message is pinned in the room')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional expiry date for temporary messages', null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='realtime_chat_messaging.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['priority', 'created_at'], name='custom_mess_priorit_163d26_idx'), models.Index(fields=['is_pinned', 'room'], name='custom_mess_is_pinn_0a4038_idx')],
            },
        ),
    ]
