# Generated by Django 6.0 on 2026-02-14 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtime_chat_messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroupChat',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realtime_chat_messaging.room')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_participants', models.PositiveBigIntegerField(default=100)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('join_approval_required', models.BooleanField(default=False)),
                ('group_locked', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('general', 'General')], db_index=True, default='general', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Group categorization tags')),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Total messages in this group')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether group is archived')),
                ('admins', models.ManyToManyField(related_name='partial_custom_groups_moderated', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'permissions': [('can_add_new_participants', 'Can add new participants'), ('can_remove_participants', 'Can remove participants')],
                'abstract': False,
                'indexes': [models.Index(fields=['department', 'is_archived'], name='partial_cus_departm_66f780_idx'), models.Index(fields=['last_activity'], name='partial_cus_last_ac_df780a_idx')],
            },
            bases=('realtime_chat_messaging.room', models.Model),
        ),
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Message tags for categorization')),
                ('read_count', models.PositiveIntegerField(default=0, help_text='Number of times message was read')),
                ('importance_score', models.IntegerField(default=0, help_text='Calculated importance score')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='realtime_chat_messaging.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['priority', 'created_at'], name='partial_cus_priorit_3ae4ce_idx'), models.Index(fields=['importance_score'], name='partial_cus_importa_a9fdf4_idx')],
            },
        ),
    ]
