# Generated by Django 6.0 on 2026-02-01 22:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences', models.JSONField(default=dict)),
                ('archived', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('last_message', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.REALTIME_CHAT_MESSAGING_MESSAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='custommessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.REALTIME_CHAT_MESSAGING_ROOM_MODEL),
        ),
        migrations.AddField(
            model_name='custommessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField()),
                ('last_seen', models.DateTimeField()),
                ('device_type', models.CharField(default='unknown', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomChannel',
            fields=[
                ('customroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.REALTIME_CHAT_MESSAGING_ROOM_MODEL)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('max_subscribers', models.PositiveBigIntegerField(default=300)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_new_subscribers', 'Can add new subscribers'), ('can_remove_subscribers', 'Can remove subscribers'), ('can_send_messages', 'Can send messages')],
                'abstract': False,
            },
            bases=('custom_implementation_test_app.customroom', models.Model),
        ),
        migrations.CreateModel(
            name='CustomGroupChat',
            fields=[
                ('customroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.REALTIME_CHAT_MESSAGING_ROOM_MODEL)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_participants', models.PositiveBigIntegerField(default=100)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('join_approval_required', models.BooleanField(default=False)),
                ('group_locked', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('admins', models.ManyToManyField(related_name='custom_groups_moderated', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_new_participants', 'Can add new participants'), ('can_remove_participants', 'Can remove participants')],
                'abstract': False,
            },
            bases=('custom_implementation_test_app.customroom', models.Model),
        ),
        migrations.CreateModel(
            name='CustomOneToOneChat',
            fields=[
                ('customroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.REALTIME_CHAT_MESSAGING_ROOM_MODEL)),
                ('participants', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('custom_implementation_test_app.customroom', models.Model),
        ),
        migrations.AddIndex(
            model_name='custommessage',
            index=models.Index(fields=['content'], name='custom_impl_content_9a4afa_idx'),
        ),
        migrations.AddIndex(
            model_name='custommessage',
            index=models.Index(fields=['content', 'sender'], name='custom_impl_content_7286c2_idx'),
        ),
    ]
