# Generated by Django 6.0 on 2025-12-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
