# Generated by Django 6.0 on 2025-12-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0002_alter_channel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'permissions': [('can_add_new_subscribers', 'Can add new subscribers'), ('can_send_messages', 'Can send messages')]},
        ),
        migrations.AddField(
            model_name='groupchat',
            name='group_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='realtime_chat_messaging.message'),
        ),
    ]
