# Generated by Django 6.0 on 2025-12-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0003_alter_channel_options_groupchat_group_locked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'permissions': [('can_add_new_participants', 'Can add new participants')]},
        ),
    ]
