# Generated by Django 6.0 on 2025-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0004_alter_groupchat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnotification',
            name='notification_type',
            field=models.CharField(choices=[('REACTION', 'Reaction'), ('NEW_MESSAGE', 'New Message'), ('REPLY', 'Reply')], default='NEW_MESSAGE', max_length=64),
        ),
    ]
