# Generated by Django 6.0 on 2025-12-18 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0005_alter_chatnotification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatnotification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='recipients',
            field=models.ManyToManyField(related_name='unread_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
