# Generated by Django 6.0 on 2025-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0007_readreceipt_unique_read_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='max_subscribers',
            field=models.PositiveBigIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='max_participants',
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
