# Generated by Django 6.0 on 2025-12-21 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0008_channel_max_subscribers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'permissions': [('can_add_new_subscribers', 'Can add new subscribers'), ('can_remove_subscribers', 'Can remove subscribers'), ('can_send_messages', 'Can send messages')]},
        ),
        migrations.AlterModelOptions(
            name='groupchat',
            options={'permissions': [('can_add_new_participants', 'Can add new participants'), ('can_remove_participants', 'Can remove participants')]},
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_reaction'),
        ),
    ]
