# Generated by Django 6.0 on 2025-12-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0009_alter_channel_options_alter_groupchat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_room', to='realtime_chat_messaging.message'),
        ),
    ]
