# Generated by Django 6.0 on 2025-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0010_room_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemediaasset',
            name='caption',
            field=models.CharField(blank=True, null=True),
        ),
    ]
