# Generated by Django 6.0 on 2025-12-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0012_alter_messagemediaasset_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemediaasset',
            name='media_url',
            field=models.CharField(),
        ),
    ]
