# Generated by Django 6.0 on 2026-01-06 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat_messaging', '0013_alter_messagemediaasset_media_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered_to',
            field=models.ManyToManyField(related_name='messages_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
